version: "2"
services:
  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
